scope: knb-lter-cap
identifier: 641
baseURL: https://data.gios.asu.edu/datasets/cap/
project: lter
title: 'Point-count bird censusing: long-term monitoring of bird abundance and diversity along the Salt River in the greater Phoenix metropolitan area, ongoing since 2013'
maintenance: regular
geographic_description: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan area and surrounding Sonoran desert region'
